name: Apply Supabase migrations & seeds
on:
  workflow_dispatch:
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set DB URL
        run: echo "SUPABASE_DB_URL=postgresql://postgres:${{ secrets.SUPABASE_DB_PASSWORD }}@db.${{ secrets.SUPABASE_PROJECT_ID }}.supabase.co:5432/postgres" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm ci
      - name: Apply migrations
        run: npm run db:push
      - name: Seed data
        run: npm run db:seed
      - name: Verify counts
        run: |
          psql $SUPABASE_DB_URL -c "SELECT COUNT(*) FROM familias;"
          psql $SUPABASE_DB_URL -c "SELECT COUNT(*) FROM modelos;"
          psql $SUPABASE_DB_URL -c "SELECT COUNT(*) FROM consumibles;"
          psql $SUPABASE_DB_URL -c "SELECT COUNT(*) FROM templates_mp;"
          psql $SUPABASE_DB_URL -c "SELECT COUNT(*) FROM wo;"
