name: Apply Supabase migrations & seeds
on:
  workflow_dispatch:
  push:
    paths:
      - 'supabase/migrations/**'
      - 'supabase/seed/**'
      - '.github/workflows/apply-supabase.yml'
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Build DB URL (Supabase pooled connection)
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          echo "DB_URL=postgresql://postgres.${SUPABASE_PROJECT_ID}:${SUPABASE_DB_PASSWORD}@aws-1-sa-east-1.pooler.supabase.com:6543/postgres" >> $GITHUB_ENV

      - name: Apply migrations
        run: supabase db push --db-url "$DB_URL"

      - name: Seed ATLANTIS (catalog)
        if: ${{ hashFiles('supabase/seed/0001_atlantis.sql') != '' }}
        # --- CORRECCIÓN AQUÍ ---
        run: psql "$DB_URL" -f supabase/seed/0001_atlantis.sql

      - name: Seed demo (clients/equipment/WO)
        if: ${{ hashFiles('supabase/seed/0002_demo_data.sql') != '' }}
        # --- CORRECCIÓN AQUÍ ---
        run: psql "$DB_URL" -f supabase/seed/0002_demo_data.sql

      - name: Verify counts
        # --- CORRECCIÓN AQUÍ ---
        run: |
          psql "$DB_URL" <<'SQL'
          select 'familias' as table, count(*) from product_family
          union all
          select 'modelos' , count(*) from product_model
          union all
          select 'consumibles', count(*) from consumable
          union all
          select 'templates_mp', count(*) from service_template
          union all
          select 'wo', count(*) from work_order;
          SQL
