name: Apply Supabase migrations & seeds
on:
  workflow_dispatch:
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Supabase CLI
        run: curl -sL https://supabase.com/cli/install | bash
      - name: Apply migrations
        run: supabase db push
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      - name: Seed data
        run: supabase db seed
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      - name: Verify counts
        run: |
          psql $SUPABASE_DB_URL -c "SELECT COUNT(*) FROM familias;"
          psql $SUPABASE_DB_URL -c "SELECT COUNT(*) FROM modelos;"
          psql $SUPABASE_DB_URL -c "SELECT COUNT(*) FROM consumibles;"
          psql $SUPABASE_DB_URL -c "SELECT COUNT(*) FROM templates_mp;"
          psql $SUPABASE_DB_URL -c "SELECT COUNT(*) FROM wo;"
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
