- name: Instalar Homebrew
  run: |
    sudo apt-get update
    sudo apt-get install -y build-essential procps curl file git
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $GITHUB_ENV
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

- name: Instalar Supabase CLI con Homebrew
  run: |
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    brew install supabase/tap/supabase
    echo "$(/home/linuxbrew/.linuxbrew/bin/brew --prefix)/bin" >> $GITHUB_PATH

- name: Verificar instalación
  run: supabase --version
