name: Instalar Supabase CLI

on:
  workflow_dispatch:

jobs:
  install-supabase-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Descargar Supabase CLI
        run: |
          SUPABASE_VERSION=$(curl -s https://api.github.com/repos/supabase/cli/releases/latest | grep tag_name | cut -d '"' -f 4 | sed 's/v//')
          wget https://github.com/supabase/cli/releases/download/v${SUPABASE_VERSION}/supabase_linux_amd64.tar.gz
          tar -xzf supabase_linux_amd64.tar.gz
          chmod +x supabase
          sudo mv supabase /usr/local/bin/supabase

      - name: Verificar instalación
        run: supabase --version
