# Nombre del flujo de trabajo
name: Desplegar Migraciones a Supabase

# Define cuándo se debe ejecutar este flujo de trabajo
on:
  # Se activa cada vez que subes cambios (haces un "push")
  push:
    # Específicamente a la rama "main"
    branches:
      - main

# Define los trabajos que se ejecutarán
jobs:
  # Nombre del trabajo
  deploy-migrations:
    # Se ejecutará en una máquina virtual con la última versión de Ubuntu
    runs-on: ubuntu-latest

    # Define los pasos que se ejecutarán en orden
    steps:
      # Paso 1: Descarga el código de tu repositorio a la máquina virtual
      - name: Checkout del código
        uses: actions/checkout@v3

      # Paso 2: Instala la CLI (Interfaz de Línea de Comandos) de Supabase
      - name: Instalar Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # Paso 3: Ejecuta el comando para aplicar las migraciones a la base de datos
      - name: Aplicar migraciones de la base de datos
        run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
