# Nombre de tu flujo de trabajo.
name: Desplegar Migraciones a Supabase

# Se ejecutará cada vez que hagas un "push" a tu rama principal.
on:
  push:
    branches:
      - main

# Trabajos a realizar.
jobs:
  deploy-migrations:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar tu código.
      - name: Checkout del código
        uses: actions/checkout@v3

      # Paso 2: Instalar la CLI de Supabase. (Este paso es el mismo de antes)
      - name: Instalar Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # ¡NUEVO! Paso 3: Vincular el proyecto (requiere el token de acceso).
      # El comando 'supabase link' no es interactivo aquí; se usa el flag --project-ref
      # que deberás añadir a tus variables de entorno si lo necesitas.
      # Una forma más directa es usar 'db push' que usa las variables de entorno.
      
      # ¡NUEVO y MEJORADO! Paso 3: Aplicar las migraciones de la base de datos.
      - name: Aplicar migraciones de la base de datos
        run: supabase db push
        env:
          # Aquí le pasamos los secrets que creamos a la CLI.
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
